# Generated by Django 3.2.7 on 2021-09-23 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('receivable_Date', models.DateTimeField(auto_now_add=True)),
                ('roll_no_of_student', models.CharField(max_length=256)),
                ('name_of_student', models.CharField(max_length=256)),
                ('class_of_student', models.CharField(max_length=256)),
                ('section_of_student', models.CharField(max_length=256)),
                ('fee_receivable', models.CharField(max_length=256)),
                ('received_Date', models.DateField(blank=True, null=True)),
                ('fee_received', models.CharField(max_length=256)),
                ('fee_added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
