# Generated by Django 3.2.7 on 2021-09-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='fee_received',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
